name: VestigiumNether
version: '${project.version}'
main: com.vestigium.vestigiumnether.VestigiumNether
api-version: '1.21'
description: Antecedent Nether lore systems, faction quests, soul roads
authors: [ Lord-Lofi ]
load: POSTWORLD
depend:
  - VestigiumLib

commands:
  vnnether:
    description: VestigiumNether administrative commands
    usage: /vnnether terminal <set|remove|list>
    permission: vestigium.nether.admin
    permission-message: §cYou do not have permission to use this command.

permissions:
  vestigium.nether.admin:
    description: Administrative access to VestigiumNether systems
    default: op
