name: VestigiumStructures
version: '${project.version}'
main: com.vestigium.vestigiumstructures.VestigiumStructures
api-version: '1.21'
description: Custom structure injection, wandering dungeons, structure NPC spawning
authors: [ Lord-Lofi ]
load: POSTWORLD
depend:
  - VestigiumLib

permissions:
  vestigium.structures.admin:
    description: Manage structure registrations and wandering dungeon placements
    default: op
