name: VestigiumNPC
version: '${project.version}'
main: com.vestigium.vestigiumnpc.VestigiumNPC
api-version: '1.21'
description: Villager memory, traveling NPCs, doppelgangers, and special NPCs
authors: [ Lord-Lofi ]
load: POSTWORLD
depend:
  - VestigiumLib
softdepend:
  - ProtocolLib

commands:
  vcbounty:
    description: Bounty Board interaction and administration
    usage: /vcbounty <take <n>|abandon|status|board <place <type>|remove>>

permissions:
  vestigium.npc.admin:
    description: Access to VestigiumNPC administrative functions
    default: op
    children:
      vestigium.admin: true
  vestigium.bounty.admin:
    description: Administer bounty boards (place/remove)
    default: op
