name: VestigiumEnd
version: '${project.version}'
main: com.vestigium.vestigiumend.VestigiumEnd
api-version: '1.21'
description: End biomes, pre-Shattering lore systems, End civilization structures
authors: [ Lord-Lofi ]
load: POSTWORLD
depend:
  - VestigiumLib
