name: VestigiumAtmosphere
version: '${project.version}'
main: com.vestigium.vestigiumatmosphere.VestigiumAtmosphere
api-version: '1.21'
description: Custom weather events, biome particle atmosphere, sky events
authors: [ Lord-Lofi ]
load: POSTWORLD
depend:
  - VestigiumLib

permissions:
  vestigium.atmosphere.admin:
    description: Manage atmospheric event overrides
    default: op
